import '../styles/global.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import Header from '@/components/Header'
import Provider from "@/components/Provider";
import Footer from "@/components/Footer";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'CoinSynch',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang='en'>
        <body>
        <Provider>
            <div className='main'>
                <div className='gradient'/>
            </div>

            <main className='app'>
                <Header/>
                {children}
                <Footer/>
            </main>
        </Provider>
        </body>
        </html>
    )
}
